import os

# main.py
SPACE_WIDTH = 30
MAX_FILENAME_LENGTH = 255
DESKTOP_PATH = os.path.expanduser("~/Desktop")
SPECIAL_CHARACTERS = {
    '!': 'Exclamation',
    '?': 'Question',
    "'": 'Apostrophe',
    '*': 'Asterisk',
    ')': 'Bracket-Left',
    '}': 'Bracket-Left-2',
    ']': 'Bracket-Left-3',
    '(': 'Bracket-Right',
    '{': 'Bracket-Right-2',
    '[': 'Bracket-Right-3',
    '^': 'Caret',
    ':': 'Colon',
    '$': 'Dollar',
    '=': 'Equals',
    '>': 'Greater-than',
    '-': 'Hyphen',
    '∞': 'Infinity',
    '<': 'Less-than',
    '#': 'Number',
    '%': 'Percent',
    '.': 'Period',
    '+': 'Plus',
    '"': 'Quotation',
    ';': 'Semicolon',
    '/': 'Slash',
    '~': 'Tilde',
    '_': 'Underscore',
    '|': 'Vertical-bar',
    ',': 'Comma',
    '&': 'Ampersand',
    '♥': 'Heart',
    '©': 'Copyright',
    '⛶': 'Square',
    'Ⅰ': 'One',
    'Ⅱ': 'Two',
    'Ⅲ': 'Three',
    'Ⅳ': 'Four',
    'Ⅴ': 'Five',
    '◀': 'Left',
    '▲': 'Up',
    '▶': 'Right',
    '▼': 'Down',
    '★': 'Star',
    '⋆': 'Mini-Star',
    '☞': 'Hand',
    '¥': 'Yen',
    '♪': 'Musical-Note',
    '︷': 'Up-Arrow',
    'ȧ': 'TODO',
    'ä': 'TODO',
    'ā': 'TODO',
    'á': 'TODO',
    'à': 'TODO',
    'â': 'TODO',
    'ã': 'TODO',
    'í': 'TODO',
    'ü': 'TODO',
    'ū': 'TODO',
    'ú': 'TODO',
    'ė': 'TODO',
    'ë': 'TODO',
    'é': 'TODO',
    'ê': 'TODO',
    'ö': 'TODO',
    'ō': 'TODO',
    'ó': 'TODO',
    'ô': 'TODO',
    'õ': 'TODO'
}

# console-version.py, windowed-version.py
VALID_COLORS_BY_FONT = {
    1: ["Blue", "Orange-1", "Orange-2"],
    2: ["Blue", "Orange-1", "Orange-2"],
    3: ["Blue", "Orange-1", "Yellow"],
    4: ["Blue", "Orange-1", "Yellow"],
    5: ["Orange-1"]
}
CLOSING_MESSAGE = "Closing..."