from pathlib import Path

SPACE_WIDTH = 30
DESKTOP_PATH = Path.home() / 'Desktop'
SPECIAL_CHARACTERS = {
    '!': 'Exclamation',
    '?': 'Question',
    "'": 'Apostrophe',
    '*': 'Asterisk',
    ')': 'Bracket-Left',
    '}': 'Bracket-Left-2',
    ']': 'Bracket-Left-3',
    '(': 'Bracket-Right',
    '{': 'Bracket-Right-2',
    '[': 'Bracket-Right-3',
    '^': 'Caret',
    ':': 'Colon',
    '$': 'Dollar',
    '=': 'Equals',
    '>': 'Greater-than',
    '-': 'Hyphen',
    '∞': 'Infinity',
    '<': 'Less-than',
    '#': 'Number',
    '%': 'Percent',
    '.': 'Period',
    '+': 'Plus',
    '"': 'Quotation',
    ';': 'Semicolon',
    '/': 'Slash',
    '~': 'Tilde',
    '_': 'Underscore',
    '|': 'Vertical-bar',
    ',': 'Comma',
    '&': 'Ampersand',
    '♥': 'Heart',
    '©': 'Copyright',
    '⛶': 'Square',
    'Ⅰ': 'One',
    'Ⅱ': 'Two',
    'Ⅲ': 'Three',
    'Ⅳ': 'Four',
    'Ⅴ': 'Five',
    '◀': 'Left',
    '▲': 'Up',
    '▶': 'Right',
    '▼': 'Down',
    '★': 'Star',
    '⋆': 'Mini-Star',
    '☞': 'Hand',
    '¥': 'Yen',
    '♪': 'Musical-Note',
    '︷': 'Up-Arrow',
    'ȧ': 'A-1',
    'ä': 'A-2',
    'ā': 'A-3',
    'á': 'A-4',
    'à': 'A-5',
    'â': 'A-6',
    'ã': 'A-7',
    'í': 'I-1',
    'ü': 'U-1',
    'ū': 'U-2',
    'ú': 'U-3',
    'ė': 'E-1',
    'ë': 'E-2',
    'é': 'E-3',
    'ê': 'E-4',
    'ö': 'O-1',
    'ō': 'O-2',
    'ó': 'O-3',
    'ô': 'O-4',
    'õ': 'O-5'
}

VALID_COLORS_BY_FONT = {
    1: ["Blue", "Orange-1", "Orange-2"],
    2: ["Blue", "Orange-1", "Orange-2"],
    3: ["Blue", "Orange-1"],
    4: ["Blue", "Orange-1"],
    5: ["Orange-1"]
}
CLOSING_MESSAGE = "\nClosing...\n"
