name: Build MetalSlugFontReborn Ubuntu

on:
  push:
    branches:
      - Development
    paths:
      - '.github/workflows/build-ubnutu.yml'

jobs:
  build:
    runs-on: ubnutu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.13'

    - name: Create a virtual environment
      run: |
        python3 -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        pip install PySide6 pillow pyinstaller

    - name: Build MetalSlugFontReborn
      run: |
        pyinstaller --noconfirm --onedir --windowed --optimize "2" --strip --name "MetalSlugFontReborn" --clean --add-data "Assets:Assets/" --add-data "Src/special_characters.py:." --add-data "Src/image_generation.py:." --add-data "Src/themes.py:." --add-data "Src/qt_utils.py:." --add-data "Src/info.py:." --add-data "Docs/SUPPORTED.txt:."  "Src/qt-version.py"

    - name: Move Assets folder
      run: |
        mv dist/MetalSlugFontReborn/_internal/Assets dist/MetalSlugFontReborn/
        mv dist/MetalSlugFontReborn/_internal/SUPPORTED.txt dist/MetalSlugFontReborn/
      shell: bash

    - name: Get short commit hash
      id: vars
      run: echo "::set-output name=short_commit::$(git rev-parse --short HEAD)"

    - name: Upload MetalSlugFontReborn
      uses: actions/upload-artifact@v4
      with:
        name: MetalSlugFontReborn-${{ steps.vars.outputs.short_commit }}-Linux-x64-Qt
        path: dist/MetalSlugFontReborn
