name: Build Ubuntu

permissions:
  contents: read

on:
  push:
    branches:
      - Development
    paths:
      - '.github/workflows/**'
      - 'Assets/**'
      - 'Src/**'
      - 'versionfile.txt'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a

      - name: Set up Python
        uses: actions/setup-python@v751276eafca55f10f252026015f43c488f2322ba
        with:
          python-version: '3.14.7'
          architecture: 'x64'
          cache: 'pip'

      - name: Get short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: pip install --upgrade PySide6-Essentials pyinstaller pillow tomlkit

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed --strip --name "MetalSlugFontReborn" --clean --optimize "2" --add-data "Src/image_generation.py:." --add-data "Src/qt_utils.py:." --add-data "Src/special_characters.py:." --add-data "Src/themes.py:." --add-data "Src/utils.py:." --add-data "Src/advanced_editor:." --add-data "Assets:Assets/"  "Src/qt-version.py"

      - name: Move Assets
        run: |
          mv dist/MetalSlugFontReborn/_internal/Assets dist/MetalSlugFontReborn/

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: MetalSlugFontReborn-${{ steps.sha.outputs.short_sha }}-Linux-x64
          path: dist/MetalSlugFontReborn
          compression-level: 9
