name: Build macOS

permissions:
  contents: read

on:
  push:
    branches:
      - Development
    paths:
      - '.github/workflows/**'
      - 'Assets/**'
      - 'Src/**'
      - 'versionfile.txt'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14.6'
          architecture: 'arm64'
          cache: 'pip'

      - name: Get short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: pip install --upgrade PySide6-Essentials pyinstaller pillow

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed --strip --name "MetalSlugFontReborn" --clean --optimize "2" --add-data "Src/image_generation.py:." --add-data "Src/qt_utils.py:." --add-data "Src/special_characters.py:." --add-data "Src/themes.py:." --add-data "Src/utils.py:." --add-data "Docs/SUPPORTED.txt:." --add-data "Assets:Assets/"  "Src/qt-version.py"

      - name: Move Assets and SUPPORTED.txt
        run: |
          mv dist/MetalSlugFontReborn/_internal/Assets dist/MetalSlugFontReborn/
          mv dist/MetalSlugFontReborn/_internal/SUPPORTED.txt dist/MetalSlugFontReborn/

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: MetalSlugFontReborn-${{ steps.sha.outputs.short_sha }}-macOS-ARM64
          path: dist/MetalSlugFontReborn
          compression-level: 9
